name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_API_VAR: ${{ vars.OPENAI_API_VAR }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CodeReview
        uses: anc95/ChatGPT-CodeReview@main
        env:
          LANGUAGE: Korean
      - name: Echo
        run: |
          echo "github token: $GITHUB_TOKEN"
          echo "openai key: $OPENAI_API_KEY"
          echo "api var: $OPENAI_API_VAR"
          
